USE PROYECTO2
GO
-----------------MAESTROS DETALLE DIEGO-----------------
SELECT
    R.RES_Id AS [ID DE LA RESERVA],
    FI.FIN_Nombre AS [NOMBRE DEL USUARIO],
    TR.TPR_Descripcion AS [TIPO DE RESERVA],
    R.RES_FechaInicio AS [FECHA DE INICIO],
    R.RES_FechaFin AS [FECHA DE FIN],

    FROM RESERVA R
    INNER JOIN USUARIOS U ON R.USR_Id = U.USR_Id
    INNER JOIN FICHAS_INSCRIPCION FI on U.FIN_Id = FI.FIN_Id
    INNER JOIN TIPO_RESERVA TR on R.TPR_Id = TR.TPR_Id

